version: '3.9'
services:
  web:
    build: .
    command: python myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fcard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CARlos99
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
